import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/component/header/header";

// const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({
  subsets: ["latin-ext"],
  weight: ["400", "600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
